blank_issues_enabled: true
contact_links:
  - name: BrandBlitz Documentation
    url: https://github.com/BrandBlitz/brandblitz/tree/main/docs
    about: Read the official documentation for BrandBlitz.
